#include <avr/io.h>
#define	F_CPU 8000000UL
#include <util/delay.h>
#include "LCD_INTERFACE.h"
#include "BUTTON_FUNC.h"
#define BUTTON_PORT 'D'
uint_8 c1,c2,c3;
void main(void)
{
	LCD_4_BIT_INIT(HIGH_NIPPLE);
	MOVE_CURSOR_4_BIT(1,5);
	LCD_WRITE_STRING_4_BIT("WELCOME");
	MOVE_CURSOR_4_BIT(2,6);
	LCD_WRITE_STRING_4_BIT("E.V.M!");
	_delay_ms(500);
	LCD_SEND_CMD_FOUR_BIT(0x01,HIGH_NIPPLE);
	MOVE_CURSOR_4_BIT(1,1);
	LCD_WRITE_STRING_4_BIT("N1=0");
	MOVE_CURSOR_4_BIT(1,11);
	LCD_WRITE_STRING_4_BIT("N2=0");
	MOVE_CURSOR_4_BIT(2,5);
	LCD_WRITE_STRING_4_BIT("N3=0");
	BUTTON_INIT(BUTTON_PORT,0);
	BUTTON_INIT(BUTTON_PORT,1);
	BUTTON_INIT(BUTTON_PORT,2);
	BUTTON_INIT(BUTTON_PORT,6);
	DIO_SET_PIN_DIRECTION(BUTTON_PORT,5,PIN_OUTPUT);
    while(1)

    {
		if (BUTTON_READ_STATE(BUTTON_PORT,0)==0)
		{
			c1++;
			MOVE_CURSOR_4_BIT(1,4);
			if(c1<10)
			{
				LCD_SEND_DATA_FOUR_BIT(c1+48,HIGH_NIPPLE);
			}
			if(c1>=10)
			{
				LCD_SEND_DATA_FOUR_BIT((c1/10)+48,HIGH_NIPPLE);
				LCD_SEND_DATA_FOUR_BIT((c1%10)+48,HIGH_NIPPLE);
			}
			while(BUTTON_READ_STATE(BUTTON_PORT,0)==0);
			DIO_PORT_PIN_WRITE(BUTTON_PORT,5,PIN_HIGH);
			_delay_ms(200);
			DIO_PORT_PIN_WRITE(BUTTON_PORT,5,PIN_LOW);
			
		}
		else if(BUTTON_READ_STATE(BUTTON_PORT,1)==0)
		{
			c2++;
			MOVE_CURSOR_4_BIT(1,14);
			if(c2<10)
			{
				LCD_SEND_DATA_FOUR_BIT(c2+48,HIGH_NIPPLE);
			}
			else if(c2>=10)
			{
				LCD_SEND_DATA_FOUR_BIT((c2/10)+48,HIGH_NIPPLE);
				LCD_SEND_DATA_FOUR_BIT((c2%10)+48,HIGH_NIPPLE);
			}
			while(BUTTON_READ_STATE(BUTTON_PORT,1)==0);
			DIO_PORT_PIN_WRITE(BUTTON_PORT,5,PIN_HIGH);
			_delay_ms(200);
			DIO_PORT_PIN_WRITE(BUTTON_PORT,5,PIN_LOW);
		}
		else if(BUTTON_READ_STATE(BUTTON_PORT,2)==0)
		{
			c3++;
			MOVE_CURSOR_4_BIT(2,8);
			if(c3<10)
			{
				LCD_SEND_DATA_FOUR_BIT(c3+48,HIGH_NIPPLE);
			}
			else if (c3>=10)
			{
				LCD_SEND_DATA_FOUR_BIT((c3/10)+48,HIGH_NIPPLE);
				LCD_SEND_DATA_FOUR_BIT((c3%10)+48,HIGH_NIPPLE);
			}
			while(BUTTON_READ_STATE(BUTTON_PORT,2)==0);
			DIO_PORT_PIN_WRITE(BUTTON_PORT,5,PIN_HIGH);
			_delay_ms(200);
			DIO_PORT_PIN_WRITE(BUTTON_PORT,5,PIN_LOW);
		}
		else if(BUTTON_READ_STATE(BUTTON_PORT,6)==0)
		{
			c1=0;
			c2=0;
			c3=0;
			LCD_SEND_CMD_FOUR_BIT(0x01,HIGH_NIPPLE);
			MOVE_CURSOR_4_BIT(1,5);
			LCD_WRITE_STRING_4_BIT("WELCOME");
			MOVE_CURSOR_4_BIT(2,6);
			LCD_WRITE_STRING_4_BIT("E.V.M!");
			_delay_ms(500);
			LCD_SEND_CMD_FOUR_BIT(0x01,HIGH_NIPPLE);
			MOVE_CURSOR_4_BIT(1,1);
			LCD_WRITE_STRING_4_BIT("N1=0");
			MOVE_CURSOR_4_BIT(1,11);
			LCD_WRITE_STRING_4_BIT("N2=0");
			MOVE_CURSOR_4_BIT(2,5);
			LCD_WRITE_STRING_4_BIT("N3=0");
		}
		_delay_ms(200);
    }
	
}